### ISSUE TITLE
1. User accessing with phone.

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#1]
Brief Description : User wants to access their account through phone.
Primary user : User
Secondary user : ATM
Trigger - the user selects the option to access their account with their phone. 

Flow of Events 
a. The user places their phone against the NFC reader of the ATM. 
b. The machine reads information from the user's phone. 
c. The machines checks the ID of the user and retrieves data from the data base. 
d. The machine displays basic personal information of the user on screen. (retrieved by the database)
e. The user is prompted for their password in order to access the account. 
f. The machine checks the password and continues to process. 

Postconditions: User must have a phone and the ATM can't be in a busy state where it cannot process the signal from the user. 
Success Postcondition(s) [a.k.a. the Success Guarantee]: User is granted permission to access their account through phone. 

Failure Postcondition(s) [a.k.a. the Minimal Guarantee] :User cannot access the account by phone

Extension Points:None

**Comment by danielpjack** [comment]
Done!
