### ISSUE TITLE
> 11. Check Balance

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#10]
Brief Description : This User case describes the situation where user wants to check the balance of their account
Primary User : User
Secondary user : ATM
Trigger - the user selects the Check Balance option.
Flow of Events 
a. The user selects the Check Balance option. 
b. The machine starts to search for the users matching ID in the database. 
d. The machine brings back the corresponding amount of money from the database (which have the matching ID)
e. The machine send the user a panel with all of the information and displays it. 
f. The machine also give the user choice to whether exit of execute another process.
h. The user checks the amount, and select one of the option to continue. 

Special Requirements : The user has a cheque to deposit into account 
Preconditions: The user has selected the “Deposit Cheque” option
Postconditions
Success Postcondition(s) [a.k.a. the Success Guarantee]: The ATM has successfully scanned the correct amount indicated on the cheque and confirmed by User. The ATM has then updated the User's selected account by the correct amount.

Failure Postcondition(s) [a.k.a. the Minimal Guarantee]: The ATM was unable to get a specified amount from the cheque or the amount found on the cheque was not confirmed by the user. User's bank account is not updated by any amount.
Extension Points: none

**Comment by lioperei** [comment]
Implemented
