### ISSUE TITLE
> 12. Change PIN

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#11]
Brief Description : This User case describes the situation where the user wants to change the PIN number 
Primary User : User 
Secondary users: the machine
triggers: the user decides to change their pin.

Flow of events:
a. the user selects the options menu from the main screen.
b. the user selects change pin from the list of options
c. the user is prompted to enter their current pin
d. the user must enter their new pin.
e. the user is prompted to re enter their pin
f. the user is then shown a confirmation screen with an option to go back to the main menu
g. the machine updates the database.

Special Requirements: none 

Pre-conditions: User has passed verification phase and check the option to change their password.
Postconditions 
Success Postcondition(s) [a.k.a. the Success Guarantee] : User successfully at changing their password.
Failure Postcondition(s) [a.k.a. the Minimal Guarantee] : User is not successful at changing their password and taken back to the main screen.
Extension Points: none.

**Comment by mgdanna** [comment]
Donezo. Had to add inputString = ""; to inputPIN()  and changePIN() so that it's possible to re-log/input anything after logging in with PIN to begin with. Maybe we should clear inputString in resetValues()
