### ISSUE TITLE
> 13. Select Account: Allows user to select which account to draw from, chequeing savings etc.

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#12]
Brief Description : This User case describes the situation where they get the option to choose between differents account
Primary User : User
Secondary users: the machine.
triggers: the user selects the option to switch between their accounts.

Flow of events:
a. the user selects an option that they can choose the account that they can work with
b. The machine gets the signal and checks available account from the users database
c. After checking all of the possible accounts the machine returns a panel where the all of the accounts are present
d. The user chooses one account 
e. The machine receives a signal that contains the information regarding the newly chosen account. 
f. The user is present back to the main frame with the changed account as default

Special Requirements: none 

Pre-conditions: User has passed verification phase and have multiple accounts where they can choose from.
Postconditions 
Success Postcondition(s) [a.k.a. the Success Guarantee] : User successfully change the default account
Failure Postcondition(s) [a.k.a. the Minimal Guarantee] : User is not successful at changing the account and taken back to the main frame.
Extension Points: none.

**Comment by danielpjack** [comment]
Implemented
