### ISSUE TITLE
'>14. Print Receipt: Prints information about user's withdrawal. Includes current balance as well as amount withdrawn.

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#13]
Brief Description : This User case describes the situation where the machine prints out a information regarding the users balance.
Primary User : User 
Secondary users: the machine
triggers: the user selects the option to print a receipt
Flow of events:
a. User selects an option where they receives a receipt. 
b. The machine reads the signal and sends it to the main system.
c. the machine creates a formatted string that includes all of the relevant information (ie. date, withdrawal amount, current balance)
d. the machine sends the string to printer.
e. the receipt is printed.
f. the user receives the receipt and proceeds on. 

Special Requirements : none 
Preconditions : The user must have enough money to send and the account must exist.

Postconditions Successful Post conditions : The user is presented with a message telling them that the money was succesfully sent.
Failure Post conditions : The user is not presented with the message and the transfer fails.
Extension Points : none

**Comment by danielpjack** [comment]
Implemented.
