### ISSUE TITLE
> 15. Transfer Money between accounts

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#14]
Brief Description : This User case describes a situation where the user wants to transfer money between two accounts. 
Primary User : User 
Secondary User : ATM 
Triggers : In the main frame the user selects the option to send money to another account. 

Flow of Events
a. The user selects the option to send money to another account. 
b. The machine gets that information and process it, returns a corresponding panel to the main frame.
c. The user inputs the account number of which they want to send the money to. 
d. The machine check if that account exist and returns the next panel.
e. The user inputs the amount of money they want to send 
f. The machine checks if there are enough amount of money in the users account if there are no error, then subtract the amount of money from the users account and add that amount to the given account.
g. The machine sends a success message back to the main frame

Special Requirements : none 
Preconditions : The user must have enough money to send and the account must exist.

Postconditions Successful Post conditions : The user is presented with a message telling them that the money was succesfully sent.
Failure Post conditions : The user is not presented with the message and the transfer fails.
Extension Points : none

**Comment by danielpjack** [comment]
Implemented.
