### ISSUE TITLE
> 16. Change Display Language

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#15]
Brief Description : This User case describes the change display language process, and it is called from the main frame when the user presses the corresponding button. 

Primary user : User 
Secondary User : ATM 
Triggers :in the main frame user chooses the correct button to change the language display option and that signal is successfully processed to the ATM machine. 
Flow of Events 
a. From the main frame the user selects the option to change the language.
b. The machine receives the signal and returns the corresponding panel back to the main frame.
c. The user selects the language of their choice and returns the signal back to the user.
d. The machine receives the signal and find the corresponding data that are represented by the language of the users choice from the database. 
f. The user is presented a new main frame with the language of their choice.

Special Requirements : none 
Preconditions : the user must have a preference for a language, and the machine cannot be in a busy state in order to process the signal.

Postconditions Successful Postconditions : The user is presented with the operating system with the language of their choice.
Failure Postconditions : The user is not presented with the operating system of their choice and the ATM makes no progress.
Extension Points : none

**Comment by danielpjack** [comment]
Added three language options.
