### ISSUE TITLE
> 17. Credit Card/Insurance/Electronic Bill Payment

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#16]
Brief Description : This User case describes the general payment process. This use case is called from the ATM machine when the user chooses the correct responding button. 
Primary Actors : User 
Secondary Actor : ATM 
Trigger : User selects an option to pay a certain bill by the ATM and not physically. 
Flow of Events a. The User selects the option to pay bill from the main screen 
b. The machine gives a list of choice, of what kins of bill that they can pay.
c. The user selects on of the options from the list. 
d. The machine process that signal and returns a corresponding panel to the main frame.
e. The user is asked to put in a amount they they want to pay and to press OK after. f. The machine gets the OK signal and process the information, such as if the user have the right amount of money in their account 
g. If no error the machine successfully transfers the money to the other account, and prints out the done panel to the main frame. 

Special Requirements : none 

Preconditions : There must be an account where the user can send money to. 

Postconditions

Success Postconditions : The user succesfully transfer the amount of money to the account they wanted. 
Failure Postconditions : The user was not able to send the money to the other account, because there was an error with one of the processing procedure

Extension Points : none

**Comment by danielpjack** [comment]
Implemented
