### ISSUE TITLE
`> 8. AF: Invalid amount (0 or > Balance)

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#17]
Brief Description : This User case describes the process where the user enters an invalid withdrawal amount. 
Primary user : User
Secondary User : ATM System
Triggers - when the user inputs invalid amount of money during the withdrawing process. 
Flow of Events
a. The amount entered is either not divisible by available bills, greater than balance, greater than account limit.
b. An error is displayed to the screen with an option to either return to previous screen. Special Requirements: none 
Preconditions : User has accessed their account through NFC or card and PIN login procedure, and is in withdraw window
Postconditions 
Success Postcondition(s) [a.k.a. the Success Guarantee] : The user is returned to Withdrawal Screen 
Failure Postcondition(s) [a.k.a. the Minimal Guarantee] : the user cannot withdraw any money.
Extension Points: none

**Comment by lioperei** [comment]
Completed
