### ISSUE TITLE
BUG 1: Overpaying Debt/Negative input value

### ISSUE THREAD

**Issue by mgdanna** [Calvin0630/cps406_s5_group-13-_w16#18]
When inputting a negative value into Debt, ATM displays it as positive, and trying to pay it off results in adding to it.

If debt overpaid, then debt is set to the difference overpaid.
Eg. $Debt = 100, Pay $101, Debt = $1
Can't pay this debt off anymore, will only add to it.

(Are we just taking the absolute value of debt and outputting it? If paying is only simple subtraction this would make sense)

**Comment by lioperei** [comment]
Proposed solution
Commit:  526ec47

**Comment by danielpjack** [comment]
As I said in chat, you should be able to overpay. Credit cards let you do this. The value shown should then be negative. However, the money formatting may be forcing a positive value, so we'll have to add a - in case of negative number
