### ISSUE TITLE
> 2. AF: Incorrect information on NFC phone / Inactivity timeout

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#2]
Brief Description : This User Case describes the Incorrect Information process
Primary User : ATM
Secondary User : User 
Trigger - invalid input of the user`s password. 

Flow of Events.
a. The machine compares the password with the password in the database. 
b. The machine identifies the input password as incorrect. 
c. The machine sends the user with a message telling that they have inputted an invalid password.
d. The machine gives a choice whether to continue on or to exit. 
d. If the user chooses to continue the process above (after e) is repeated. 

Special Requirements : none
Preconditions: the user must input a wrong Password from his phone, also the ATM machine have successfully compare the two passwords. One from the database and the other from the user. 
Postconditions

Success Postcondition(s) [a.k.a. the Success Guarantee]: the user is successfully as whether if they want to exit or to retry entering the password.

Failure Postcondition(s) [a.k.a. the Minimal Guarantee]: the user is not asked whether if they want to exit or to retry. And the ATM machine does not make any progress
Extension Points: none

**Comment by danielpjack** [comment]
Five done!
