### ISSUE TITLE
BUG 8: Input can take unnecessarily gigantic numbers

### ISSUE THREAD

**Issue by mgdanna** [Calvin0630/cps406_s5_group-13-_w16#25]
Input for chequing/savigs/debt can be astronomical, causes slight overlap issues on screen and makes paying off bills functionally impossible by not being able to see how many digits remain.

![image](https://cloud.githubusercontent.com/assets/17029124/14150878/33161d42-f679-11e5-8093-2352592994e8.png)

Should probably limit all fields to 6 or 7 digits.

**Comment by lioperei** [comment]
Added possible solution
Commit:  1c38387
