### ISSUE TITLE
> 3. User accessing with card

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#3]
Brief Description : User wants to access their account through card.
Primary User : User Secondary User : ATM Trigger : User sends a signal to the ATM indicating that he wants to access his account through card 

Flow of events 
a.The user selects the option, to access their account though card. 
b. The machine process the signal the returns the corresponding panel to the main frame.
c. The user is asked to input the card of their choice into the machine. 
d. The machine reads the users card and processes it. 
e. If there are no errors then the user is presented with a welcome panel, that contains all of the options they can perform. 

Special Requirements: none 
Preconditions : User must have the card ready, ATM must not be busy and be ready to process the signal from the user 
Postconditions 
Success Postcondition(s) [a.k.a. the Success Guarantee] : the user is granted access to their account by card.
Failure Postcondition(s) [a.k.a. the Minimal Guarantee] : the user cannot access their account by card. 
Extension Points: none

**Comment by danielpjack** [comment]
Two done!
