### ISSUE TITLE
> 5. User enters pin

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#5]
Brief Description : This User case describes a situation where the user wants to input their PIN number. 
Primary User : User
Secondary User : ATM
Triggers - User wants to access the next step of their process, however there is security matter involved.

Flow of Events

a. The user chooses an option that requires a security verification. 
b. The machine receives a signal from the user panel, and returns a panel with a location for PIN number. 
c. The user is prompted for their PIN number. 
d. As the user inputs the number, the machine masks each character as \* on screen.
e. The user presses the next button to go to the next step.
f. The machine compared the two PIN number and check whether if they match or not. The one that the user have inputted and the one in the database. 
g. If there are no errors then the user is presented with the next screen. 

Postconditions: User must have choose an option where they need security verification. 
Success Postcondition(s) [a.k.a. the Success Guarantee]: User is granted permission to access the next step. 

Failure Postcondition(s) [a.k.a. the Minimal Guarantee] :User cannot access to the next step.

Extension Points:None

**Comment by danielpjack** [comment]
Three done!
