### ISSUE TITLE
> 6. AF: Incorrect PIN / Inactivity Timeout

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#6]
Brief Description : This User case describes a situation where user input an incorrect PIN or user's session time have ran out. 
Primary User : ATM
Secondary User : the user who inputted the wrong pin/ user who waited too long. 
Triggers - the user either inputted a wrong pin number or they waited too long, so the system have terminated. 

Flow of Events
a. The machine compares the two PIN number one received by the user and the other the one in the database. 
b. The machine sends a error signal to the main system, indicating an error.
c. The main system returns a panel, that corresponds to the indicated error. 
d. The user is presented by the panel, that gives them the option whether to input the number again or exit out. 
e. The user chooses any option to proceed. 

a. The machine's session time sends a signal to the main system, tell it that the user time have expired. 
b. The machine tells the user that their session is over, and the user have start from the beginning. 
c. The machine give a choice to the user either to start again or to exit.
d. The user chooses any option to proceed. 

Special Requirements : none

**Comment by danielpjack** [comment]
Four! Done the Incorrect portion, combining the timeout with UC#2
