### ISSUE TITLE
> 7. User withdrawing money

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#7]
Brief Description : This User case describes a situation where the user withdraws money from their account. 
Primary User : User
Secondary User : ATM
Triggers - the user press a button to get the money out of their account. 

Flow of Events
a. The user presses a button to withdraw money. 
b. The machine displays all available accounts to withdraw money from. 
c. The user selects an account. d. The machine displays preset withdraw amounts as well as a custom option. 
e. The user either selects a preset or custom and inputs the amount of money they want. 
f. The machine checks for the amount and whether it is a valid amount (eg. multiple of 10) 
g. The machine checks if the withdraw amount is greater than the account total and if not, continues. 
h. The machine withdraws the money. 
i. The machine asks the user if they want a receipt or to exit. 
j. The user chooses their option and the ATM either exits or prints a receipt then exits. 

Special Requirements: none 
Preconditions : User has accessed their account through NFC or card and PIN login procedure. 
Postconditions 
Success Postcondition(s) [a.k.a. the Success Guarantee] : the user withdraws a valid amount of money.
Failure Postcondition(s) [a.k.a. the Minimal Guarantee] : the user cannot withdraw any money. 
Extension Points: none. 

AF: Invalid amount (0 or > Balance)
`> 8. AF: Invalid amount (0 or > Balance)
Brief Description : This User case describes the process where the user enters an invalid withdrawal amount. 
Primary user : User
Secondary User : ATM System
Triggers - when the user inputs invalid amount of money during the withdrawing process. 
Flow of Events
a. The amount entered is either not divisible by available bills, greater than balance, greater than account limit.
b. An error is displayed to the screen with an option to either return to previous screen. Special Requirements: none 
Preconditions : User has accessed their account through NFC or card and PIN login procedure, and is in withdraw window
Postconditions 
Success Postcondition(s) [a.k.a. the Success Guarantee] : The user is returned to Withdrawal Screen 
Failure Postcondition(s) [a.k.a. the Minimal Guarantee] : the user cannot withdraw any money.
Extension Points: none

**Comment by lioperei** [comment]
Completed
