### ISSUE TITLE
> 9. User deposits cash

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#8]
Brief Description : This User case describes a situation where user deposit cash
Primary user : User

Secondary User : ATM 

Triggers - the user selects the Deposit option. 

Flow of Events

a. The user selects the option to deposit money. 
b. The machine displays the user's accounts and prompts the user to select which account to deposit into.
c. The machine send a panel to the user asking the method of their input. 
d. The user selects their option and the process continues. 
e. The machine displays the corresponding panel to the user. 
f. The machine ask for the money to be inputted to the retrieving box. 
g. The machine counts the money, and how much they have inputted. 
h. The machines ask for a confirmation regarding the amount of money. 
i. The user confirms the amount. 
j. The machine adds the amount to the user's account. 
k. The machine informs the user and ask whether to exit or to do another operation. 
l. The user select their option and continues on. 

Special Requirements: none 
Preconditions : User has accessed their account through NFC or card and PIN login procedure and have the money to deposit
Postconditions 
Success Postcondition(s) [a.k.a. the Success Guarantee] : the user is successful at depositing the money.
Failure Postcondition(s) [a.k.a. the Minimal Guarantee] : the user is not succesful at depositing their money. 
Extension Points: none.

**Comment by danielpjack** [comment]
Implemented
