### ISSUE TITLE
> 10. User deposits cheque

### ISSUE THREAD

**Issue by Calvin0630** [Calvin0630/cps406_s5_group-13-_w16#9]
Brief Description : The operation of the ATM system in the case of user depositing by cheque.
Primary Actor: User
Secondary Actor: ATM System
Trigger: User has selected to deposit a cheque.

Flow of events:
a. User has selected to deposit by cheque.
b. System prepares for insertion of cheque.
c. System takes in cheque.
d. Using interior hardware (camera) and recognition software, gets amount represented by cheque.
May have error.
e. Confirms with user amount on cheque.
Either correct, or error.

Special Requirements : The user has cash to deposit into account 
Preconditions: The user has selected the “Deposit Cash”
Postconditions
Success Postcondition(s) [a.k.a. the Success Guarantee]: The ATM has successfully collected the correct amount of cash set by the User and has then updated the User's selected account by the correct amount.
Failure Postcondition(s) [a.k.a. the Minimal Guarantee]: The ATM was unable to get a specified amount and times out. User's bank account is not updated by any amount and any cash provided is returned to the user.
Extension Points: none

**Comment by danielpjack** [comment]
Implemented
